### ISSUE TITLE
Leave/telework shortcut URL is 404ing

### ISSUE THREAD

**Issue by brittag** [18F/handbook-urls#9]
The handbook table of content links to https://handbook.18f.gov/leave-telework-and-virtual-work - but that currently goes to a 404 page. ([Here's the handbook page it intends to point to.](https://github.com/18F/handbook/blob/staging/articles/3-policies/leave-telework-and-virtual-worker.md))

**Comment by melodykramer** [comment]
fixed.

**Comment by brittag** [comment]
Since I was momentarily confused while looking at this (since the URL was still 404ing), just noting that this has been fixed by updating the relevant links to https://handbook.18f.gov/leave-telework-and-virtual-worker. :)
